# Generated by Django 5.2.16 on 2026-07-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
